[package]
name = "grape-lex"
version = "0.1.0"
edition = "2021"

[dependencies]
grape-diagnostics = { path = "../grape-diagnostics" }
grape-span = { path = "../grape-span" }
grape-symbol = { path = "../grape-symbol" }
grape-token = { path = "../grape-token" }
